### ISSUE TITLE
Invalid standard handle identifier: 4294967286

### ISSUE THREAD

**Issue by d-sphinx** [kaosagnt/toolbox2docker#1]
20.10.3, clean install

`C:\Users\User>docker ps
panic: Invalid standard handle identifier: 4294967286

goroutine 1 [running]:
github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winterm.GetStdFile(0xf
ffffff6, 0xc00009c738, 0xb)
        /go/src/github.com/docker/cli/vendor/github.com/Azure/go-ansiterm/winter
m/ansi.go:173 +0x1f3
github.com/docker/cli/vendor/github.com/moby/term/windows.NewAnsiReader(0xffffff
f6, 0xc00000000f, 0x20d5920)
        /go/src/github.com/docker/cli/vendor/github.com/moby/term/windows/ansi_r
eader.go:34 +0x36
github.com/docker/cli/vendor/github.com/moby/term.StdStreams(0xc0002f61a0, 0xc00
04e5eb8, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/cli/vendor/github.com/moby/term/term_windows.g
o:75 +0x1eb
github.com/docker/cli/cli/command.NewDockerCli(0x0, 0x0, 0x0, 0x19ba58c, 0x1b500
e0, 0xc000234180)
        /go/src/github.com/docker/cli/cli/command/cli.go:473 +0x1a7
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:291 +0x4b`

**Comment by d-sphinx** [comment]
![image](https://user-images.githubusercontent.com/4455753/106868152-7d3fb780-66df-11eb-9095-113f83ad8407.png)

**Comment by kaosagnt** [comment]
Seems to be a known issue.

https://github.com/docker/cli/issues/2911

You might want to try the work around until the Docker people fix it.

https://github.com/docker/for-win/issues/9770#issuecomment-745106453

**Comment by d-sphinx** [comment]
A workaround seems to be working only for Windows 10 and not Windows 7 (cause there is no such option 'Use legacy console').

Which is the latest version of toolbox2docker not introducing this bug?

**Comment by kaosagnt** [comment]
I'd say all of the 20.10 releases contain the bug.

Try https://github.com/kaosagnt/toolbox2docker/releases/tag/19.03.14

**Comment by abelcheung** [comment]
Encountering same issue on Windows 7. Other than downgrading docker, there is an alternative: execute `docker.exe` under Bash on Windows — either Git Bash or MingW Bash works fine. BTW I have just tried most current release (20.10.6), and can confirm issue is _not_ fixed.

**Comment by kaosagnt** [comment]
Thanks for the latest test and your work around. Alas I fear the Docker people won't fix this unless enough people complain.

**Comment by kaosagnt** [comment]
Pinning so people can find the work around. Closing.
