### ISSUE TITLE
Curl not working in docker host

### ISSUE THREAD

**Issue by sebthom** [kaosagnt/toolbox2docker#11]
In the latest release curl does not work anymore in the docker host complaining about a missing `libzstd.so.1`

```sh
> docker-machine ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
docker@default:~$ curl
curl: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
```

**Comment by kaosagnt** [comment]
Thanks for the report. Looks like TCL curl is compiled with zstd support now.
I have added the necessary TCL library in the iso build.

docker@default:~$ curl -V
curl 8.4.0 (x86_64-pc-linux-gnu) libcurl/8.4.0 OpenSSL/3.2.0 zlib/1.2.13 zstd/1.5.5
Release-Date: 2023-10-11
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS HSTS HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP UnixSockets zstd

You can download the iso from:
https://github.com/kaosagnt/boot2docker-xfs-ng/releases/tag/25.0.0

and copy into your docker machine directory

${HOME}/.docker/machine/machines/{machine_name}

I shall roll updated toolbox2docker installers shortly.

**Comment by kaosagnt** [comment]
New installers available at https://github.com/kaosagnt/toolbox2docker/releases/tag/25.0.0p1

**Comment by sebthom** [comment]
Works, thanks for the quick fix!
