### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by sebthom** [kaosagnt/toolbox2docker#2]
Hey Ian,

just wanted to thank you for the work you put into maintaining this docker toolbox fork.

I need to use virtualbox and docker at the same time on my windows workstation - which does not work with docker desktop as it requires hyper-v. enabling hyper-v however still renders virtualbox completely unusable.

Kind Regards,
Seb

**Comment by kaosagnt** [comment]
Thanks for the kind words.
