### ISSUE TITLE
Docker-machine fetches obsolete boot2docker iso by default

### ISSUE THREAD

**Issue by abelcheung** [kaosagnt/toolbox2docker#3]
Problem is noticed when `docker-machine` creates the initial VM under Windows host. It completely ignores bundled ISO image (but I have installed `toolbox2docker` in non-default location under `D:\something`, not sure if it matters), and tries to pull ISO from the now-archived boot2docker. It only allowed me to use the new xfs enabled ISO with `--virtualbox-boot2docker-url` option specified.

While patching and recompiling docker-machine is a very hefty price to pay for small problem like this. how about a few forewarning words in README?

**Comment by kaosagnt** [comment]
I knew about this but hadn't decided what to do. I haven't wanted to maintain a fork of yet another docker component before coming across the Gitlab fork of docker-machine with has more issues fixed but still will fetch the obsolete boot2docker ISO. I'll add the note to the README. Thanks for the report.
