### ISSUE TITLE
How to use bundled boot2docker iso?

### ISSUE THREAD

**Issue by sebthom** [kaosagnt/toolbox2docker#4]
I am trying to use toolbox2docker on Windows 10. As reported in #3 I also realized that an old boot2docker.iso file is downloaded by default.

However it does not seem to be possible on Windows to reference the `boot2docker.iso` file that comes with toolbox2docker. No matter what kind of file URL I try to feed into the `--virtualbox-boot2docker-url` parameter of docker-machine I either receive:
```
Error creating machine: Error in driver during machine creation: open .../boot2docker.iso: The filename, directory name, or volume label syntax is incorrect.
```
or
```
Error creating machine: Error in driver during machine creation: Panic in the driver: runtime error: invalid memory address or nil pointer dereference
goroutine 71 [running]:
runtime/debug.Stack(0x1a37bc0, 0x0, 0x22988c0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
github.com/docker/machine/libmachine/drivers/rpc.(*StandardStack).Stack(0x36c2fc0, 0x1a37bc0, 0x368c050, 0x22988c0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:23 +0x29
github.com/docker/machine/libmachine/drivers/rpc.trapPanic(0xc00018fc00)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:129 +0x9b
panic(0x1a37bc0, 0x368c050)
        /usr/local/go/src/runtime/panic.go:522 +0x1c3
github.com/docker/machine/libmachine/mcnutils.(*b2dReleaseGetter).download(0xc0001485b0, 0xc00042b280, 0x33, 0x1e3dd30, 0xf, 0xc0000b0080, 0x31, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/mcnutils/b2d.go:198 +0x67
github.com/docker/machine/libmachine/mcnutils.(*B2dUtils).DownloadISO(0xc000076b40, 0xc00042b280, 0x33, 0x1e3dd30, 0xf, 0xc0000b0080, 0x31, 0xc0002bf7c8, 0xc0002bf7c8)
        /go/src/github.com/docker/machine/libmachine/mcnutils/b2d.go:357 +0x17b
github.com/docker/machine/libmachine/mcnutils.(*B2dUtils).CopyIsoToMachineDir(0xc000076b40, 0xc0000b0080, 0x31, 0xc0004987b0, 0x7, 0xc0002bf8a0, 0x5758c4)
        /go/src/github.com/docker/machine/libmachine/mcnutils/b2d.go:461 +0x43c
github.com/docker/machine/drivers/virtualbox.(*b2dUtilsUpdater).CopyIsoToMachineDir(0x36c3468, 0xc0000ae060, 0x22, 0xc0004987b0, 0x7, 0xc0000b0080, 0x31, 0x16, 0x1b1da80)
        /go/src/github.com/docker/machine/drivers/virtualbox/misc.go:27 +0x76
github.com/docker/machine/drivers/virtualbox.(*Driver).CreateVM(0xc000287900, 0xc000092040, 0x28)
        /go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:300 +0x92
github.com/docker/machine/drivers/virtualbox.(*Driver).Create(0xc000287900, 0x1eb2898, 0xc0002bfc00)
        /go/src/github.com/docker/machine/drivers/virtualbox/virtualbox.go:291 +0x36
github.com/docker/machine/libmachine/drivers/rpc.(*RPCServerDriver).Create(0xc00023fb40, 0x36c3468, 0x36c3468, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/drivers/rpc/server_driver.go:140 +0x6c
reflect.Value.call(0xc0000c94a0, 0xc00050e120, 0x13, 0x1e2e94b, 0x4, 0xc0002bff18, 0x3, 0x3, 0xc000152000, 0xd40010, ...)
        /usr/local/go/src/reflect/value.go:447 +0x468
reflect.Value.Call(0xc0000c94a0, 0xc00050e120, 0x13, 0xc0002bff18, 0x3, 0x3, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:308 +0xab
net/rpc.(*service).call(0xc000528000, 0xc0000de460, 0xc000096040, 0xc000096050, 0xc00051aa00, 0xc00008ef60, 0x184b4c0, 0x36c3468, 0x16, 0x184b4c0, ...)
        /usr/local/go/src/net/rpc/server.go:384 +0x155
created by net/rpc.(*Server).ServeCodec
        /usr/local/go/src/net/rpc/server.go:481 +0x432
```

I installed toolbox2docker to C:\apps\dev\toolbox2docker and I tried these URLs:
```
file:///C/apps/dev/toolbox2docker/boot2docker.iso
file://C/apps/dev/toolbox2docker/boot2docker.iso
file:///C:/apps/dev/toolbox2docker/boot2docker.iso
file://C:/apps/dev/toolbox2docker/boot2docker.iso
file:///C:\apps\dev\toolbox2docker\boot2docker.iso
file://C:\apps\dev\toolbox2docker\boot2docker.iso
```

Any ideas?

In the meantime I am pointing `--virtualbox-boot2docker-url` directly to https://github.com/kaosagnt/boot2docker-xfs-ng/releases/download/20.10.7/boot2docker.iso

**Comment by kaosagnt** [comment]
In my script for creating virtual machine on macOS i use:

BOOT2DOCKER_URL="--${VIRTUAL_DRIVER}-boot2docker-url file://localhost/Users/ianm/.docker/machine/cache/boot2docker.iso"

after copying the boot2docker.iso file into that location.

In your case try:

file://localhost/c/apps/dev/toolbox2docker/boot2docker.iso

**Comment by sebthom** [comment]
That unfortunately also doesn't work:

```
Creating machine...
(default) Downloading C:\Users\user1\.docker\machine\cache\boot2docker.iso from file://localhost/C/apps/dev/toolbox2docker/boot2docker.iso...
Error creating machine: Error in driver during machine creation: open /C/apps/dev/toolbox2docker/boot2docker.iso: The system cannot find the path specified.
```

I also tried adding the drive letter colon (:) without success as in `file://localhost/C:/apps/dev/toolbox2docker/boot2docker.iso`

**Comment by kaosagnt** [comment]
Hi, sorry for the delay.

I have forked docker/machine and changed the api end point to point to the kaosagnt/boot2docker-xfs-ng ISO releases.

The version tests in docker/machine appear to be broken so even when you copied the ISO into the ${HOME}/.docker/machine/cache area docker machine this that v19.03.12 is greater the v20.10.8 and would still download the depreciated ISO.

(test-url) Calling .PreCreateCheck
(test-url) DBG | local Boot2Docker ISO version:  v20.10.8
(test-url) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(test-url) Latest release for github.com/boot2docker/boot2docker is v19.03.12
(test-url) Downloading /Users/ianm/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso..

So I have forked docker/machine.

Can you please try down loading docker/machine from:

https://github.com/kaosagnt/docker-machine/releases/tag/v0.16.2-gitlab.13-t2d.1

If you're using a built in driver like VirtualBox this should work fine. If you're using an external driver such as

https://github.com/machine-drivers/docker-machine-driver-vmware

you will still encounter issues as the external drivers compile an old libmachine that still point to the depreciated boot2docker ISO API URL.

I'll be shipping the changed docker/machine binary in the next Toolbox2docker release. 

Hopefully you should see something like the following

C:\Users\ianm\Desktop>docker-machine-Windows-x86_64.exe create -d virtualbox tes
t-url2
Running pre-create checks...
(test-url2) Default Boot2Docker ISO is out-of-date, downloading the latest relea
se...
(test-url2) Latest release for github.com/kaosagnt/boot2docker-xfs-ng is 20.10.8

(test-url2) Downloading C:\Users\ianm\.docker\machine\cache\boot2docker.iso from
 https://github.com/kaosagnt/boot2docker-xfs-ng/releases/download/20.10.8/boot2d
ocker.iso...
(test-url2) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%...
.100%
Creating machine...
(test-url2) Default Boot2Docker ISO is out-of-date, downloading the latest relea
se...
(test-url2) Latest release for github.com/kaosagnt/boot2docker-xfs-ng is 20.10.8

(test-url2) Downloading C:\Users\ianm\.docker\machine\cache\boot2docker.iso from
 https://github.com/kaosagnt/boot2docker-xfs-ng/releases/download/20.10.8/boot2d
ocker.iso...
(test-url2) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%...
.100%
(test-url2) Copying C:\Users\ianm\.docker\machine\cache\boot2docker.iso to C:\Us
ers\ianm\.docker\machine\machines\test-url2\boot2docker.iso...
(test-url2) Creating VirtualBox VM...
(test-url2) Creating SSH key...
(test-url2) Starting the VM...
(test-url2) Check network to re-create if needed...
(test-url2) Windows might ask for the permission to configure a dhcp server. Som
etimes, such confirmation window is minimized in the taskbar.
(test-url2) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this vi
rtual machine, run: docker-machine-Windows-x86_64.exe env test-url2

**Comment by kaosagnt** [comment]
The latest release of Toolbox2docker now ships with docker-machine that points to the kaosagnt/boot2docker-xfs-ng ISO.

https://github.com/kaosagnt/toolbox2docker/releases/tag/20.10.9
