### ISSUE TITLE
How to increase available disk space?

### ISSUE THREAD

**Issue by d-sphinx** [kaosagnt/toolbox2docker#5]
Hello, this is not an issue but rather a question (don't know how to ask it directly):

I stumbled upon lack of space for docker images and containers. So, is it possible to increase virtual disk space after installation, or, at least somehow choose appropriate size before? 20 Gb is very small nowadays.

Thank you!

**Comment by kaosagnt** [comment]
Not easily as there is no LVM installed. Your bet bet is to create a new virtual machine with the size you are after.

docker-machine create --driver virtualbox --help

   --virtualbox-disk-size "20000"		Size of disk for host in MB [$VIRTUALBOX_DISK_SIZE]
