### ISSUE TITLE
change docker-machine ip address

### ISSUE THREAD

**Issue by d-sphinx** [kaosagnt/toolbox2docker#7]
Hello! This is not an issue, actually, but rather a question: how to change local IP address used by docker?

$ docker-machine ip
192.168.99.105

I would like to change it back to 192.168.99.101 which I used to - is it possible?
Thank you.

**Comment by kaosagnt** [comment]
Sorry for the late reply, I generally use VMware Fusion under macOS. You may have to go into the Host Network Manager settings and adjust things there under VirtualBox. 

![image](https://user-images.githubusercontent.com/18473913/214808178-053b5eb9-98c1-4230-9e77-5eb2bc0d6dd9.png)

**Comment by kaosagnt** [comment]
Closing
