### ISSUE TITLE
Don't preselect "Help Docker improve Toolbox" and "Kitematic" in installer

### ISSUE THREAD

**Issue by sebthom** [kaosagnt/toolbox2docker#8]
I don't know if it is possible, but would be great if you could change the installer to not enable these options by default:

![image](https://user-images.githubusercontent.com/426959/216787712-79d39a7c-223a-4ae4-8af3-59adeea01c22.png)

![image](https://user-images.githubusercontent.com/426959/216787721-e4f50c2c-3842-401a-85ab-7d0c686ec63b.png)

**Comment by kaosagnt** [comment]
Some of these are on my TODO list.

There has been enough time for a transition to compose 2.x.x so the old 1.9.x will be removed with plans for removing Kitematic entirely.

The Telemetry thing is something I want to remove but haven't found time to track down how it works. I think it set an ENV variable allowing possibly docker cli or machine cli but I need to find time to follow that though.

**Comment by kaosagnt** [comment]
Release 23.0.1 https://github.com/kaosagnt/toolbox2docker/releases/tag/23.0.1 removes:

Kitematic from the installer.
Docker Compose 1.29.x from the installer.

The Telemetry (Help Improve) has been deselected by default in the Windows installer. The macOS installer requires rebuilding using Xcode to do this, so it will have to wait until I remove the telemetry gathering altogether.

**Comment by sebthom** [comment]
Just installed it. Works like a charm. Thanks a lot!
