### ISSUE TITLE
Question: is VirtualBox 7.x (f.e. 7.0.8) supported?

### ISSUE THREAD

**Issue by lospejos** [kaosagnt/toolbox2docker#9]
This is rather a question that an issue.

Toolbox2Docker supports separate installations along with VirtualBox.
Currently I do use VirtualBox 6.x to be able to work with Toolbox2Docker.
I'm wondering if I can upgrade my VirtualBox to version 7.x (f.e. 7.0.8) and will be supported this VirtualBox version (7.0.8) by current Toolbox2Docker (23.0.5)?

Any help appreciated.

**Comment by kaosagnt** [comment]
Hi,

The Boot2docker-xfs-ng iso has the Virtualbox GA 7.0.8 client, so this should work if you update to Virtualbox 7.0.8.
In theory unless the Virtualbox CLI has changed 7.0.8 should work unless your using macOS.

The reason I have not looked at Virtualbox 7.x yet is that on macOS the Virtualbox developers did the following:

https://www.virtualbox.org/wiki/Changelog-7.0#v8

VirtualBox 7.0.0 (released October 10 2022)

macOS host: Dropped all kernel extensions. [VirtualBox](https://www.virtualbox.org/wiki/VirtualBox) relies fully on the hypervisor and vmnet frameworks provided by Apple now. At the moment the implementation lacks "Internal Networking" functionality. This will be provided at a later date.

--

"Internal Networking" functionality is required for Toolbox2docker to function correctly.

While VirtualBox 7.0.2 (released October 20 2022) states:

macOS hosts: Re-introduced support for internal networking, this is considered a bit experimental still

--

I'm waiting for the macOS "Internal Networking" to be not in the experimental state before I look at shipping Virtualbox 7.x with Toolbox2docker.

I generally use this software under macOS and not windows. If your a windows user, hopefully things will work correctly and if you do test and it works, then I could ship 6.x for macOS installation and 7.x for windows users.

**Comment by lospejos** [comment]
Thanks for your reply. I'll try to use Toolbox2docker with VirtualBox 7.0.8 om Windows and share results here.

**Comment by lospejos** [comment]
I've tested `Toolbox2docker` version `23.0.5` with `VirtualBox` version `7.0.8` on `Windows 10 IOT LTSC` host, and it seems that is works fine.
